# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leonardo Daniel Serrano Luna
title: Mechanical and Electrical Engineer
email: serranolunal@gmail.com
website: www.github.com/LeonardoSerranoL

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  LeonardoSerranoL
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: LeonardoDanielSerranoLuna
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Leonardo Serrano and I'm a skilled Mechanical and Electrical Engineer, specialized in Finite Element Analysis and Systems Mechanical Design. As well as I have experience in programming languages. 
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institut National des Sciences Appliquées de Toulouse (INSA Toulouse)
        caption: September 2022 - January 2023
        sub_title: Mechanical Engineering
        quote: >
          The Institut National des Sciences Appliquées de Toulouse is a French grande école of engineering, under the authority of the French Ministry of Education and Research. Situated in Toulouse, this school is one of the 6 state engineering institutes that compose the INSA's network.
The school was founded in 1963 to train highly qualified engineers, foster continuous training and scientific research. It is a member of the University of Toulouse since 2007. Even though INSA Toulouse is highly selective, diversity and international openness are two values to which INSA Toulouse gives priority
        description: | # this will include new lines to allow paragraphs
          During my time at INSA I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          
          I worked in several projects as Mechanical Power Transmission Systems using CATIA, Post Buckling Effects in Aeronautical Structures using Abaqus and Mechanical Systems Design using Dymola

          I developed my social skills participating in Foreign Activities, Judo's classes and 
          
    content:
      - layout: left
        title: Benemérita Universidad Autónoma de Puebla
        caption: August 2018 - Est 2023
        sub_title: Mechanical and Electrical Engineering
        quote: >
          The Benemérita Universidad Autónoma de Puebla (BUAP) is a Mexican university based in Puebla. The university was founded by Spanish Jesuits on 14 April 1578 as the Colegio del Espíritu Santo (College of the Holy Spirit), and became a public university after Mexican independence in 1825. It belongs to the 150 international schools and institutions that are members of the ALICE experiment launched by the European Organization for Nuclear Research (CERN).
        description: | # this will include new lines to allow paragraphs
          During my time at BUAP I have adquired my knowledge, scientific and human skills to excell in the global context the I have participated in several courses as "Introduction to the Finite Element Analysis" [2021] and "Machine Learning with Python" [2022].
          
          I have been staff volunteer for the Covid Vaccination days


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
